### ISSUE TITLE
Windows Node Pool

### ISSUE THREAD

**Issue by jamesmoriarty** [Dynatrace/dynatrace-oneagent-operator#218]
Hey, does the operator support windows node pools? e.g.

https://cloud.google.com/blog/products/containers-kubernetes/run-windows-server-containers-on-gke

**Comment by mreider** [comment]
Hi James,
The operator does not support this yet. You could probably install the Windows OS Agent directly on the nodes, but on GKE this would likely be paved over when Google updates things, as they manage the software for you. This would not give you any container based metrics, so those would have to be done using "app only" installation. Two separate sets of metrics, gathered in two different ways. Host level and App level.

The underlying issue here is that there is not equivalent to a privileged container for the host agent to inject into containers on Windows. Microsoft tells us they will support a privileged container in the second half of 2020, but we'll see. 

We do have some alternative ideas for injecting into containers using admission controllers in Kubernetes, and this is just getting off the ground within our engineering team. This will provide a way to use the Operator without the need for a host agent at all.

Hope that makes sense. Keep checking in as the year proceeds.

Matt

**Comment by jamesmoriarty** [comment]
Thanks Matt. Will experiment with what you've said.

And regarding the admission controller approach - I would love an automated alternative to the super privileged container injection.

**Comment by DTMad** [comment]
Hey @jamesmoriarty !

We are currently working on a solution to get rid of the privileged container approach.
However, this will take some time until it's officially releasable.

Once it's released we will let you know!
Hope this helps. If you need further assistance feel free to reopen this issue.

Thanks,
Marco
