### ISSUE TITLE
feature request: apiUrl  if unset, name of custom resource is used

### ISSUE THREAD

**Issue by jamesmoriarty** [Dynatrace/dynatrace-oneagent-operator#276]
For `apiUrl` could the same behaviour work as for `token`?

```
# if unset, name of custom resource is used
```

**Comment by DTMad** [comment]
This is not really possible since for our managed customers the URL might look completely different and there might also be an ActiveGate in between which would also mean a different URL.
Sorry but this isn't really feasible.

However with our new operator we are currently developing you only need to specify the URL once and it will get reused for OneAgent objects, OneAgentAPM objects, ...
Hope this helps
