### ISSUE TITLE
Resolve "latest" to the actual version

### ISSUE THREAD

**Issue by estahn** [Dynatrace/dynatrace-oneagent-operator#385]
The operator uses `latest` as a default ([see here](https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/02b89203dd17bd03fa1d20f7e44076fb060bf6df/api/v1alpha1/oneagent_types.go#L56)).

This is directly being used as the image tag.

It is best practice to not use `latest` as an image tag, but instead the actual version. The operator should resolve `latest` to the actual version of the agent.

**Comment by DTMad** [comment]
Hey @estahn !

Since the operator releases are not in sync with the OneAgent releases setting this to a fixed version is not an option.
This field is meant to allow you specifying a specific version of the OneAgent you want to use.
However since most customers would like to have their OneAgent up to date and we also wanna provide them with the latest features we are using latest here.

**Comment by estahn** [comment]
@DTMad I believe you misunderstood. The operator should request the latest version from an endpoint, e.g. GitHub or Dynatrace API and use that versioning instead of the tag latest.

The tags should be immutable. We cache them hence it's a hassle to roll out a new latest tag.

Also it's against best practices.
