### ISSUE TITLE
Uninstall process leaves files behind

### ISSUE THREAD

**Issue by makentenza** [Dynatrace/dynatrace-oneagent-operator#44]
Following the [documentation](https://github.com/Dynatrace/dynatrace-oneagent-operator/blob/master/README.md#openshift-2) for the uninstall process, all the Kubernetes objects are removed, but lots of files are left behind the process on every single Node. The uninstall process should take care about these files and removed them.

```
[root@ip-10-20-1-55 oneagent]# pwd
/opt/dynatrace/oneagent
[root@ip-10-20-1-55 oneagent]# du -hs .
894M	.
[root@ip-10-20-1-55 oneagent]# find ./ | wc -l
4460
```

**Comment by aloismayr** [comment]
Hi @makentenza,
The uninstall process leaves OneAgent binaries and configs in the filesystem in an inactive state. This is expected behavior. If you want to purge all OneAgent leftovers, please follow the instructions in our documentation. 
https://www.dynatrace.com/support/help/cloud-platforms/openshift/full-stack/operation/uninstall-oneagent-from-openshift/

**Comment by esukram** [comment]
Closing, as this is a desired behavior.
